In [1]:
import numpy as np
import seaborn as sb
import pandas as pd

In [2]:
from ucimlrepo import fetch_ucirepo
molecular_biology_splice_junction_gene_sequences = fetch_ucirepo(id=69) 
  
# data (as pandas dataframes) 
X = molecular_biology_splice_junction_gene_sequences.data.features 
y = molecular_biology_splice_junction_gene_sequences.data.targets

In [3]:
X.shape

(3190, 60)

In [4]:
X.isnull().sum()

Base1     0
Base2     0
Base3     0
Base4     0
Base5     0
Base6     0
Base7     0
Base8     0
Base9     0
Base10    0
Base11    0
Base12    0
Base13    0
Base14    0
Base15    0
Base16    0
Base17    0
Base18    0
Base19    0
Base20    0
Base21    0
Base22    0
Base23    0
Base24    0
Base25    0
Base26    0
Base27    0
Base28    0
Base29    0
Base30    0
Base31    0
Base32    0
Base33    0
Base34    0
Base35    0
Base36    0
Base37    0
Base38    0
Base39    0
Base40    0
Base41    0
Base42    0
Base43    0
Base44    0
Base45    0
Base46    0
Base47    0
Base48    0
Base49    0
Base50    0
Base51    0
Base52    0
Base53    0
Base54    0
Base55    0
Base56    0
Base57    0
Base58    0
Base59    0
Base60    0
dtype: int64

In [5]:
X.info()
attributes = X.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3190 entries, 0 to 3189
Data columns (total 60 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Base1   3190 non-null   object
 1   Base2   3190 non-null   object
 2   Base3   3190 non-null   object
 3   Base4   3190 non-null   object
 4   Base5   3190 non-null   object
 5   Base6   3190 non-null   object
 6   Base7   3190 non-null   object
 7   Base8   3190 non-null   object
 8   Base9   3190 non-null   object
 9   Base10  3190 non-null   object
 10  Base11  3190 non-null   object
 11  Base12  3190 non-null   object
 12  Base13  3190 non-null   object
 13  Base14  3190 non-null   object
 14  Base15  3190 non-null   object
 15  Base16  3190 non-null   object
 16  Base17  3190 non-null   object
 17  Base18  3190 non-null   object
 18  Base19  3190 non-null   object
 19  Base20  3190 non-null   object
 20  Base21  3190 non-null   object
 21  Base22  3190 non-null   object
 22  Base23  3190 non-null   object
 23  Base24  3190 non-null   object
 24  Base25  3190 non-null   object
 25  Base26  3190 non-null   object
 26  Base27  3190 non-null   object
 27  Base28  3190 non-null   object
 28  Base29  3190 non-null   object
 29  Base30  3190 non-null   object
 30  Base31  3190 non-null   object
 31  Base32  3190 non-null   object
 32  Base33  3190 non-null   object
 33  Base34  3190 non-null   object
 34  Base35  3190 non-null   object
 35  Base36  3190 non-null   object
 36  Base37  3190 non-null   object
 37  Base38  3190 non-null   object
 38  Base39  3190 non-null   object
 39  Base40  3190 non-null   object
 40  Base41  3190 non-null   object
 41  Base42  3190 non-null   object
 42  Base43  3190 non-null   object
 43  Base44  3190 non-null   object
 44  Base45  3190 non-null   object
 45  Base46  3190 non-null   object
 46  Base47  3190 non-null   object
 47  Base48  3190 non-null   object
 48  Base49  3190 non-null   object
 49  Base50  3190 non-null   object
 50  Base51  3190 non-null   object
 51  Base52  3190 non-null   object
 52  Base53  3190 non-null   object
 53  Base54  3190 non-null   object
 54  Base55  3190 non-null   object
 55  Base56  3190 non-null   object
 56  Base57  3190 non-null   object
 57  Base58  3190 non-null   object
 58  Base59  3190 non-null   object
 59  Base60  3190 non-null   object
dtypes: object(60)
memory usage: 1.5+ MB

In [6]:
for col in X.columns:
    print(X[col].unique())

['C' 'A' 'G' 'T' 'D']
['C' 'G' 'A' 'T' 'D']
['A' 'G' 'T' 'C']
['G' 'C' 'A' 'T']
['C' 'T' 'A' 'G']
['T' 'C' 'G' 'A']
['G' 'A' 'C' 'T']
['C' 'A' 'G' 'T']
['A' 'C' 'G' 'T']
['T' 'G' 'C' 'A']
['C' 'G' 'A' 'T']
['A' 'G' 'C' 'T']
['C' 'A' 'G' 'T']
['A' 'G' 'T' 'C' 'N']
['G' 'C' 'T' 'A']
['G' 'C' 'T' 'A']
['A' 'G' 'T' 'C']
['G' 'T' 'A' 'C']
['G' 'A' 'C' 'T' 'N']
['C' 'G' 'A' 'T' 'N']
['C' 'G' 'T' 'A' 'N']
['A' 'C' 'T' 'G' 'N']
['G' 'C' 'A' 'T' 'N']
['C' 'G' 'A' 'T' 'N']
['G' 'T' 'A' 'C' 'N']
['A' 'G' 'C' 'T' 'N']
['G' 'C' 'T' 'A' 'N']
['C' 'A' 'G' 'T' 'N']
['A' 'G' 'C' 'T' 'N']
['G' 'C' 'A' 'T' 'N']
['G' 'N' 'C' 'T' 'A']
['T' 'N' 'C' 'G' 'A']
['C' 'G' 'A' 'N' 'T']
['T' 'A' 'C' 'G' 'N']
['G' 'T' 'A' 'C' 'N' 'R']
['T' 'C' 'A' 'G' 'N' 'S']
['T' 'C' 'A' 'G' 'N']
['C' 'G' 'T' 'A' 'N']
['C' 'G' 'T' 'A' 'N']
['A' 'G' 'C' 'T' 'N']
['A' 'C' 'G' 'T' 'N']
['G' 'C' 'A' 'T' 'N']
['G' 'A' 'C' 'T' 'N']
['G' 'C' 'T' 'A' 'N']
['C' 'T' 'A' 'G' 'N']
['C' 'G' 'T' 'A' 'N']
['T' 'C' 'G' 'A' 'N']
['T' 'G' 'C' 'A' 'N']
['C' 'G' 'T' 'A' 'N']
['G' 'C' 'A' 'T' 'N']
['A' 'G' 'C' 'T' 'N']
['G' 'T' 'A' 'C' 'N']
['C' 'G' 'T' 'A' 'N']
['C' 'G' 'T' 'A' 'N']
['A' 'C' 'G' 'T' 'N']
['G' 'C' 'T' 'A' 'N']
['T' 'C' 'G' 'A' 'N']
['C' 'A' 'G' 'T' 'N']
['T' 'G' 'C' 'A' 'N']
['G' 'C' 'T' 'A' 'N']

In [7]:
X.head()

,Base1,Base2,Base3,Base4,Base5,Base6,Base7,Base8,Base9,Base10,...,Base51,Base52,Base53,Base54,Base55,Base56,Base57,Base58,Base59,Base60
0,C,C,A,G,C,T,G,C,A,T,...,A,G,C,C,A,G,T,C,T,G
1,A,G,A,C,C,C,G,C,C,G,...,G,T,G,C,C,C,C,C,G,C
2,G,A,G,G,T,G,A,A,G,G,...,C,A,C,G,G,G,G,A,T,G
3,G,G,G,C,T,G,C,G,T,T,...,G,G,T,T,T,T,C,C,C,C
4,G,C,T,C,A,G,C,C,C,C,...,C,C,T,T,G,A,C,C,C,T

In [ ]:
# Dizionario esteso per gestire anche i codici di ambiguità (sia maiuscoli che minuscoli per sicurezza)
extended_nucleotide_map = {
    'A': 0, 'a': 0,
    'C': 1, 'c': 1,
    'G': 2, 'g': 2,
    'T': 3, 't': 3,
    'N': 4, 'n': 4,
    'D': 5, 'd': 5,
    'R': 6, 'r': 6,
    'S': 7, 's': 7
}

X = pd.get_dummies(X, dtype=int)

# 2. Estrai direttamente la lista dei nuovi attributi
attributes = list(X.columns)

# 3. Estrai la matrice dei valori per addestrare la rete e l'albero
X = X.values

In [9]:
y = y.replace({'EI': 0, 'IE' : 1, 'N' : 2})

C:\Users\david\AppData\Local\Temp\ipykernel_16004\1700280817.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  y = y.replace({'EI': 0, 'IE' : 1, 'N' : 2})

In [10]:
y.head()

   class
0      0
1      0
2      0
3      0
4      0

In [11]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, classification_report
from sklearn.model_selection import StratifiedKFold, cross_val_score

In [12]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [13]:
# Addestra una rete (come nel paper)
mlp = MLPClassifier(
    hidden_layer_sizes=(64),  # prova 0,5,10,20,40
    max_iter=2000,
    random_state=42,
)
mlp.fit(X_train, y_train)
y_pred = mlp.predict(X_test)

c:\Users\david\miniconda3\envs\trepan-dev\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1219: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [14]:
print('Test Accuracy %s' % accuracy_score(y_test, y_pred))
print('Test F1-score %s' % f1_score(y_test, y_pred, average=None))
print(classification_report(y_test, y_pred))

Test Accuracy 0.9561128526645768
Test F1-score [0.94444444 0.93661972 0.97151899]
              precision    recall  f1-score   support

           0       0.94      0.95      0.94       179
           1       0.92      0.95      0.94       140
           2       0.98      0.96      0.97       319

    accuracy                           0.96       638
   macro avg       0.95      0.95      0.95       638
weighted avg       0.96      0.96      0.96       638

In [ ]:
# importa la classe direttamente dal file
from RuleTree.tree.TrepanClassifier import TrepanClassifier
trepan_clf = TrepanClassifier(estimator = mlp, s_min= 1000, max_internal_nodes= 15, prune_useless_leaves=False, random_state=42)
trepan_clf.fit(X_train, y_train)
y_pred_trepan = trepan_clf.predict(X_test)
print('Accuracy %s' % accuracy_score(y_test, y_pred_trepan))
print('F1-score %s' % f1_score(y_test, y_pred_trepan, average=None))
print(classification_report(y_test, y_pred_trepan))
fidelty = accuracy_score(y_pred, y_pred_trepan)
print("The fidelty respect to the oracle is %s" % fidelty)

c:\Users\david\miniconda3\envs\trepan-dev\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Accuracy 0.9310344827586207
F1-score [0.91495601 0.89726027 0.95489891]
              precision    recall  f1-score   support

           0       0.96      0.87      0.91       179
           1       0.86      0.94      0.90       140
           2       0.95      0.96      0.95       319

    accuracy                           0.93       638
   macro avg       0.92      0.92      0.92       638
weighted avg       0.93      0.93      0.93       638

The fidelty respect to the oracle is 0.9247648902821317

In [16]:
trepan_clf.print_trepan_rules(feature_names=attributes)

======================================================================
  REGOLE GLOBALI ESTRATTE DA TREPAN
======================================================================
REGOLA 1 [Nodo ID: Rll]:
  IF  (1-of-{ Base30_G == 0, Base29_A == 0, Base28_G == 1 }}) AND
      (1-of-{ Base32_T == 0, Base31_G == 0, Base35_G == 0 }})
  THEN Predizione = 2
  [Fedeltà: 96.68%, Copertura: 50.74%]

REGOLA 2 [Nodo ID: Rlrl]:
  IF  (1-of-{ Base30_G == 0, Base29_A == 0, Base28_G == 1 }}) AND
      (NOT (1-of-{ Base32_T == 0, Base31_G == 0, Base35_G == 0 }})) AND
      (1-of-{ Base33_T == 0, Base1_C == 0 }})
  THEN Predizione = 0
  [Fedeltà: 96.30%, Copertura: 12.70%]

REGOLA 3 [Nodo ID: Rlrr]:
  IF  (1-of-{ Base30_G == 0, Base29_A == 0, Base28_G == 1 }}) AND
      (NOT (1-of-{ Base32_T == 0, Base31_G == 0, Base35_G == 0 }})) AND
      (NOT (1-of-{ Base33_T == 0, Base1_C == 0 }}))
  THEN Predizione = 2
  [Fedeltà: 100.00%, Copertura: 0.04%]

REGOLA 4 [Nodo ID: Rrlllll]:
  IF  (NOT (1-of-{ Base30_G == 0, Base29_A == 0, Base28_G == 1 }})) AND
      (1-of-{ Base32_T == 0, Base31_G == 0, Base35_G == 0 }}) AND
      (1-of-{ Base28_A == 0, Base25_A == 0, Base6_C == 0 }}) AND
      (1-of-{ Base28_A == 0 }}) AND
      (1-of-{ Base25_G == 0, Base24_A == 0, Base54_G == 1 }}) AND
      (1-of-{ Base32_T == 0 }})
  THEN Predizione = 1
  [Fedeltà: 92.94%, Copertura: 17.20%]

REGOLA 5 [Nodo ID: Rrllllr]:
  IF  (NOT (1-of-{ Base30_G == 0, Base29_A == 0, Base28_G == 1 }})) AND
      (1-of-{ Base32_T == 0, Base31_G == 0, Base35_G == 0 }}) AND
      (1-of-{ Base28_A == 0, Base25_A == 0, Base6_C == 0 }}) AND
      (1-of-{ Base28_A == 0 }}) AND
      (1-of-{ Base25_G == 0, Base24_A == 0, Base54_G == 1 }}) AND
      (NOT (1-of-{ Base32_T == 0 }}))
  THEN Predizione = 1
  [Fedeltà: 82.81%, Copertura: 8.66%]

REGOLA 6 [Nodo ID: Rrlllr]:
  IF  (NOT (1-of-{ Base30_G == 0, Base29_A == 0, Base28_G == 1 }})) AND
      (1-of-{ Base32_T == 0, Base31_G == 0, Base35_G == 0 }}) AND
      (1-of-{ Base28_A == 0, Base25_A == 0, Base6_C == 0 }}) AND
      (1-of-{ Base28_A == 0 }}) AND
      (NOT (1-of-{ Base25_G == 0, Base24_A == 0, Base54_G == 1 }}))
  THEN Predizione = 2
  [Fedeltà: 100.00%, Copertura: 0.24%]

REGOLA 7 [Nodo ID: Rrllrll]:
  IF  (NOT (1-of-{ Base30_G == 0, Base29_A == 0, Base28_G == 1 }})) AND
      (1-of-{ Base32_T == 0, Base31_G == 0, Base35_G == 0 }}) AND
      (1-of-{ Base28_A == 0, Base25_A == 0, Base6_C == 0 }}) AND
      (NOT (1-of-{ Base28_A == 0 }})) AND
      (1-of-{ Base31_T == 0, Base58_T == 0 }}) AND
      (1-of-{ Base31_T == 0 }})
  THEN Predizione = 2
  [Fedeltà: 49.02%, Copertura: 2.00%]

REGOLA 8 [Nodo ID: Rrllrlr]:
  IF  (NOT (1-of-{ Base30_G == 0, Base29_A == 0, Base28_G == 1 }})) AND
      (1-of-{ Base32_T == 0, Base31_G == 0, Base35_G == 0 }}) AND
      (1-of-{ Base28_A == 0, Base25_A == 0, Base6_C == 0 }}) AND
      (NOT (1-of-{ Base28_A == 0 }})) AND
      (1-of-{ Base31_T == 0, Base58_T == 0 }}) AND
      (NOT (1-of-{ Base31_T == 0 }}))
  THEN Predizione = 2
  [Fedeltà: 100.00%, Copertura: 0.16%]

REGOLA 9 [Nodo ID: Rrllrr]:
  IF  (NOT (1-of-{ Base30_G == 0, Base29_A == 0, Base28_G == 1 }})) AND
      (1-of-{ Base32_T == 0, Base31_G == 0, Base35_G == 0 }}) AND
      (1-of-{ Base28_A == 0, Base25_A == 0, Base6_C == 0 }}) AND
      (NOT (1-of-{ Base28_A == 0 }})) AND
      (NOT (1-of-{ Base31_T == 0, Base58_T == 0 }}))
  THEN Predizione = 2
  [Fedeltà: 100.00%, Copertura: 0.12%]

REGOLA 10 [Nodo ID: Rrlr]:
  IF  (NOT (1-of-{ Base30_G == 0, Base29_A == 0, Base28_G == 1 }})) AND
      (1-of-{ Base32_T == 0, Base31_G == 0, Base35_G == 0 }}) AND
      (NOT (1-of-{ Base28_A == 0, Base25_A == 0, Base6_C == 0 }}))
  THEN Predizione = 0
  [Fedeltà: 95.00%, Copertura: 0.20%]

REGOLA 11 [Nodo ID: Rrrl]:
  IF  (NOT (1-of-{ Base30_G == 0, Base29_A == 0, Base28_G == 1 }})) AND
      (NOT (1-of-{ Base32_T == 0, Base31_G == 0, Base35_G == 0 }})) AND
      (1-of-{ Base28_T == 0, Base24_C == 0, Base49_G == 0 }})
  THEN Predizione = 0
  [Fedeltà: 92.50%, Copertura: 7.84%]

REGOLA 12 [Nodo ID: Rrrr]:
  IF  (NOT (1-of-{ Base30_G == 0, Base29_A == 0, Base28_G == 1 }})) AND
      (NOT (1-of-{ Base32_T == 0, Base31_G == 0, Base35_G == 0 }})) AND
      (NOT (1-of-{ Base28_T == 0, Base24_C == 0, Base49_G == 0 }}))
  THEN Predizione = 1
  [Fedeltà: 95.00%, Copertura: 0.12%]

In [17]:
def create_mlp(hidden_units):
    if hidden_units == 0:
        return MLPClassifier(
            hidden_layer_sizes=(),
            max_iter=3000,  # aumentato
            random_state=111,
            early_stopping=False,
            alpha=0.001
        )
    else:
        return MLPClassifier(
            hidden_layer_sizes=(hidden_units,),
            max_iter=3000,
            random_state=111,
            early_stopping=False,
            alpha=0.001
        )

def select_best_hidden_units(X_train, y_train, hidden_units_list, cv_inner=5):
    """
    Seleziona il miglior numero di hidden unit con cross-validation interna.
    Come nel paper: prova {0,5,10,20,40} e sceglie il migliore.
    """
    X_train = np.asarray(X_train, dtype=np.float64)
    # y_train è già int, non convertire
    
    best_units = 10
    best_score = -1
    
    for units in hidden_units_list:
        mlp = create_mlp(units)
        scores = cross_val_score(mlp, X_train, y_train, cv=cv_inner, scoring='accuracy')
        mean_score = np.mean(scores)
        
        if mean_score > best_score:
            best_score = mean_score
            best_units = units
            
    return best_units, best_score

def train_and_evaluate_network(X_train, y_train, X_test, y_test, hidden_units):
    """
    Addestra una rete neurale e restituisce:
    - accuracy sul test set
    - modello addestrato
    - predizioni sul test set
    """
    mlp = create_mlp(hidden_units)
    mlp.fit(X_train, y_train)
    y_pred = mlp.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    return acc, mlp, y_pred

In [ ]:
X_np = X
y_np = y.values  # y è già numpy array
# 10-FOLD CROSS-VALIDATION (CORRETTA!)
# ============================================================
hidden_units_list = [64,32,80]
n_folds = 10
random_state = 111

accuracies_net = []
accuracies_tree = []
fidelities = []
chosen_units = []

skf = StratifiedKFold(n_splits=n_folds, shuffle=True, random_state=random_state)

print("\n" + "="*60)
print("INIZIO 10-FOLD CV ")
print("="*60 + "\n")

for fold, (train_idx, test_idx) in enumerate(skf.split(X_np, y_np), 1):
    print(f"Fold {fold}/{n_folds}")
    
    # 1. Dividi i dati (USANDO NUMPY!)
    X_train = X_np[train_idx]
    y_train = y_np[train_idx]
    X_test = X_np[test_idx]
    y_test = y_np[test_idx]
    
    
    # 3. Seleziona hidden units
    best_units, best_cv_score = select_best_hidden_units(
        X_train, y_train, hidden_units_list, cv_inner=5
    )
    chosen_units.append(best_units)
    print(f"  → Migliori hidden units: {best_units} (CV score interno: {best_cv_score:.3f})")
    
    # 4. Addestra rete
    net_acc, network, y_pred_net = train_and_evaluate_network(
        X_train, y_train, X_test, y_test, best_units
    )
    accuracies_net.append(net_acc)
    print(f"  → Accuratezza rete: {net_acc:.3f}")
    
    # 5. TREPAN
    trepan_clf = TrepanClassifier(
        estimator=network,
        s_min=1000,
        max_internal_nodes=15,
        # 15 nodi interni + 1
        random_state=111
    )
    trepan_clf.fit(X_train, y_train)
    y_pred_trepan = trepan_clf.predict(X_test)  
    
    tree_acc = accuracy_score(y_test, y_pred_trepan)
    fidelity = accuracy_score(y_pred_net, y_pred_trepan)
    
    accuracies_tree.append(tree_acc)
    fidelities.append(fidelity)
    
    print(f"  → Accuratezza albero: {tree_acc:.3f}")
    print(f"  → Fedeltà albero-rete: {fidelity:.3f}")
    print()

print("="*60)
print("RISULTATI FINALI (10-fold CV)")
print("="*60)
print(f"Accuratezza rete:     {np.mean(accuracies_net):.3f} ± {np.std(accuracies_net):.3f}")
print(f"Accuratezza albero:   {np.mean(accuracies_tree):.3f} ± {np.std(accuracies_tree):.3f}")
print(f"Fedeltà:              {np.mean(fidelities):.3f} ± {np.std(fidelities):.3f}")
print(f"Hidden units più scelte: {pd.Series(chosen_units).value_counts().to_dict()}")

============================================================
INIZIO 10-FOLD CV - HEART DISEASE
============================================================

Fold 1/10
  → Migliori hidden units: 80 (CV score interno: 0.941)
  → Accuratezza rete: 0.925
  → Accuratezza albero: 0.928
  → Fedeltà albero-rete: 0.918

Fold 2/10
  → Migliori hidden units: 64 (CV score interno: 0.941)
  → Accuratezza rete: 0.950
  → Accuratezza albero: 0.944
  → Fedeltà albero-rete: 0.937

Fold 3/10
  → Migliori hidden units: 80 (CV score interno: 0.945)
  → Accuratezza rete: 0.966
  → Accuratezza albero: 0.918
  → Fedeltà albero-rete: 0.928

Fold 4/10
  → Migliori hidden units: 80 (CV score interno: 0.942)
  → Accuratezza rete: 0.959
  → Accuratezza albero: 0.940
  → Fedeltà albero-rete: 0.931

Fold 5/10
  → Migliori hidden units: 80 (CV score interno: 0.943)
  → Accuratezza rete: 0.950
  → Accuratezza albero: 0.931
  → Fedeltà albero-rete: 0.928

Fold 6/10
  → Migliori hidden units: 80 (CV score interno: 0.943)
  → Accuratezza rete: 0.953
  → Accuratezza albero: 0.925
  → Fedeltà albero-rete: 0.944

Fold 7/10
  → Migliori hidden units: 64 (CV score interno: 0.942)
  → Accuratezza rete: 0.937
  → Accuratezza albero: 0.925
  → Fedeltà albero-rete: 0.897

Fold 8/10
  → Migliori hidden units: 64 (CV score interno: 0.942)
  → Accuratezza rete: 0.947
  → Accuratezza albero: 0.953
  → Fedeltà albero-rete: 0.944

Fold 9/10
  → Migliori hidden units: 80 (CV score interno: 0.946)
  → Accuratezza rete: 0.944
  → Accuratezza albero: 0.937
  → Fedeltà albero-rete: 0.925

Fold 10/10
  → Migliori hidden units: 80 (CV score interno: 0.946)
  → Accuratezza rete: 0.947
  → Accuratezza albero: 0.947
  → Fedeltà albero-rete: 0.928

============================================================
RISULTATI FINALI (10-fold CV)
============================================================
Accuratezza rete:     0.948 ± 0.011
Accuratezza albero:   0.935 ± 0.011
Fedeltà:              0.928 ± 0.013
Hidden units più scelte: {80: 7, 64: 3}